# golangci-lint configuration for goimg-datalayer
# Run: golangci-lint run --config=.golangci.yml

run:
  # Timeout for analysis
  timeout: 5m

  # Include test files
  tests: true

  # Which directories to skip
  skip-dirs:
    - vendor
    - third_party
    - testdata
    - examples
    - Godeps
    - builtin

  # Which files to skip
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
    - "mock_.*\\.go$"

  # Allow multiple parallel golangci-lint instances
  allow-parallel-runners: true

# Output configuration
output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  formats:
    - format: colored-line-number

  # Print lines of code with issue
  print-issued-lines: true

  # Print linter name in the end of issue text
  print-linter-name: true

  # Make issues output unique by line
  uniq-by-line: true

  # Sort results by: filepath, line and column
  sort-results: true

# Linters configuration
linters:
  # Enable specific linters
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused constants, variables, functions and types

    # Additional recommended linters
    - asasalint     # Check for pass []any as any in variadic func(...any)
    - asciicheck    # Check for non-ASCII identifiers
    - bidichk       # Check for dangerous unicode character sequences
    - bodyclose     # Check whether HTTP response body is closed successfully
    - containedctx  # Detect struct contained context.Context field
    - contextcheck  # Check whether the function uses a non-inherited context
    - cyclop        # Check function and package cyclomatic complexity
    - dupl          # Code clone detection
    - durationcheck # Check for two durations multiplied together
    - errname       # Check that sentinel errors are prefixed with Err
    - errorlint     # Find code that will cause problems with Go 1.13+ error wrapping
    - exhaustive    # Check exhaustiveness of enum switch statements
    - exportloopref # Check for pointers to enclosing loop variables
    - forbidigo     # Forbid specific identifiers
    - funlen        # Detect long functions
    - gochecknoinits # Check that no init functions are present
    - gocognit      # Compute and check cognitive complexity of functions
    - goconst       # Find repeated strings that could be constants
    - gocritic      # Highly extensible Go linter
    - gocyclo       # Compute and check cyclomatic complexity
    - godot         # Check if comments end in a period
    - gofmt         # Check whether code was gofmt-ed
    - gofumpt       # Stricter gofmt
    - goheader      # Check file headers
    - goimports     # Check import statements are formatted according to goimport
    - gomnd         # Detect magic numbers
    - gomoddirectives # Manage the use of 'replace', 'retract', and 'excludes' directives in go.mod
    - gomodguard    # Allow and block lists for direct Go module dependencies
    - goprintffuncname # Check that printf-like functions are named with f at the end
    - gosec         # Inspect source code for security problems
    - grouper       # Analyze expression groups
    - importas      # Enforce consistent import aliases
    - interfacebloat # Check the number of methods in an interface
    - ireturn       # Accept interfaces, return concrete types
    - lll           # Report long lines
    - loggercheck   # Check key-value pairs for common logger libraries
    - maintidx      # Measure maintainability index
    - makezero      # Find slice declarations with non-zero initial length
    - misspell      # Find commonly misspelled English words
    - musttag       # Enforce field tags in (un)marshaled structs
    - nakedret      # Find naked returns in functions greater than a specified length
    - nestif        # Report deeply nested if statements
    - nilerr        # Find code that returns nil even if it checks that error is not nil
    - nilnil        # Check that there is no simultaneous return of nil error and invalid value
    - noctx         # Find sending http request without context.Context
    - nolintlint    # Report ill-formed or insufficient nolint directives
    - nonamedreturns # Report all named returns
    - nosprintfhostport # Check for misuse of Sprintf to construct a host with port
    - predeclared   # Find code that shadows one of Go's predeclared identifiers
    - promlinter    # Check Prometheus metrics naming
    - reassign      # Check that package variables are not reassigned
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - sloglint      # Ensure consistent code style when using log/slog
    - rowserrcheck  # Check whether Err of rows is checked successfully
    - sqlclosecheck # Check that sql.Rows and sql.Stmt are closed
    - stylecheck    # Stylecheck is a replacement for golint
    - tagalign      # Check that struct tags are well aligned
    - tenv          # Detect using os.Setenv instead of t.Setenv
    - testableexamples # Check if examples are testable
    - testifylint   # Checks usage of github.com/stretchr/testify
    - testpackage   # Make you use a separate _test package
    - thelper       # Detect test helpers without t.Helper() call
    - tparallel     # Detect inappropriate usage of t.Parallel()
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Report unused function parameters
    - usestdlibvars # Detect the possibility to use variables/constants from stdlib
    - wastedassign  # Find wasted assignment statements
    - whitespace    # Detect leading and trailing whitespace
    - wrapcheck     # Check that errors from external packages are wrapped

  # Disable specific linters (with reasons)
  disable:
    - deadcode      # Deprecated: replaced by unused
    - exhaustivestruct # Deprecated: replaced by exhaustruct
    - golint        # Deprecated: replaced by revive
    - ifshort       # Deprecated
    - interfacer    # Deprecated
    - maligned      # Deprecated: replaced by govet 'fieldalignment'
    - nosnakecase   # Deprecated: replaced by revive 'var-naming'
    - scopelint     # Deprecated: replaced by exportloopref
    - structcheck   # Deprecated: replaced by unused
    - varcheck      # Deprecated: replaced by unused
    - depguard      # Too restrictive for this project
    - execinquery   # Not applicable
    - exhaustruct   # Too strict for initialization
    - forcetypeassert # Handled by linting error checks
    - gci           # Conflicts with goimports
    - godox         # TODOs are acceptable in development
    - goerr113      # Too strict for custom errors
    - paralleltest  # Not all tests can be parallel
    - tagliatelle   # Tag naming is project-specific
    - varnamelen    # Short variable names are acceptable
    - wsl           # Whitespace linter is too opinionated

# Linter-specific settings
linters-settings:
  # errcheck: check for unchecked errors
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close

  # govet: reports suspicious constructs
  govet:
    enable-all: true
    disable:
      - shadow # Too strict
      - fieldalignment # Performance optimization, not correctness

  # gosec: security checker
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked (covered by errcheck)
      - G307 # Deferring a method which returns an error

  # gocyclo: cyclomatic complexity
  gocyclo:
    min-complexity: 15

  # gocognit: cognitive complexity
  gocognit:
    min-complexity: 20

  # funlen: function length
  funlen:
    lines: 100
    statements: 50
    ignore-comments: true

  # lll: line length
  lll:
    line-length: 120
    tab-width: 4

  # goconst: repeated strings
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true

  # gomnd: magic numbers
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - operation
          - return
          - assign
        ignored-functions:
          - 'strconv.*'
          - 'math.*'
          - 'http.StatusText'
        ignored-numbers:
          - '0'
          - '1'
          - '2'
          - '10'
          - '100'
          - '1000'

  # revive: configurable linter
  revive:
    severity: warning
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: cognitive-complexity
        arguments: [20]
      - name: function-length
        arguments: [50, 100]

  # stylecheck: style checker
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]
    dot-import-whitelist:
      - fmt
    initialisms: ["ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS", "IPFS", "CID"]
    http-status-code-whitelist: ["200", "400", "404", "500"]

  # gocritic: comprehensive linter
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
      - hugeParam
      - rangeValCopy
    settings:
      captLocal:
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 512

  # nakedret: naked returns
  nakedret:
    max-func-lines: 30

  # nestif: deeply nested if statements
  nestif:
    min-complexity: 5

  # cyclop: cyclomatic complexity
  cyclop:
    max-complexity: 15
    package-average: 0.0
    skip-tests: true

  # dupl: code clone detection
  dupl:
    threshold: 100

  # wrapcheck: error wrapping
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
    ignorePackageGlobs:
      - github.com/yegamble/goimg-datalayer/*

  # interfacebloat: interface size
  interfacebloat:
    max: 10

  # ireturn: return concrete types
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - generic

  # maintidx: maintainability index
  maintidx:
    under: 20

  # forbidigo: forbidden identifiers
  forbidigo:
    forbid:
      - 'fmt\.Print.*'
      - 'panic'
      - 'os\.Exit'
    exclude-godoc-examples: true

  # gomodguard: module dependencies
  gomodguard:
    blocked:
      modules:
        - github.com/sirupsen/logrus:
            recommendations:
              - github.com/rs/zerolog
            reason: "zerolog is the standard logger for this project"

  # musttag: enforce struct tags
  musttag:
    functions:
      - name: encoding/json.Marshal
        tag: json
      - name: encoding/json.Unmarshal
        tag: json
      - name: github.com/jmoiron/sqlx.Get
        tag: db
      - name: github.com/jmoiron/sqlx.Select
        tag: db

  # sloglint: slog best practices
  sloglint:
    no-mixed-args: true
    kv-only: false
    attr-only: false
    no-global: "all"
    context: "all"

  # testifylint: testify best practices
  testifylint:
    enable-all: true
    disable:
      - float-compare  # Sometimes we need exact float comparison
      - go-require     # require is acceptable in some cases

  # tagalign: align struct tags
  tagalign:
    align: true
    sort: true
    order:
      - json
      - yaml
      - xml
      - db
      - validate
      - binding

# Issues configuration
issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Maximum count of issues with the same text
  max-same-issues: 3

  # Show only new issues
  new: false

  # Fix found issues (if supported by the linter)
  fix: false

  # Exclude specific issues
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        - funlen
        - gocognit
        - cyclop
        - maintidx
        - wrapcheck

    # Exclude some linters from running on test helpers
    - path: internal/testutil/
      linters:
        - errcheck
        - gosec
        - wrapcheck

    # Exclude magic number checks in tests
    - path: _test\.go
      linters:
        - gomnd

    # Exclude function length checks in main.go
    - path: cmd/.*/main\.go
      linters:
        - funlen

    # Allow init functions in infrastructure layer
    - path: internal/infrastructure/
      text: "don't use init function"

    # Allow dot imports in tests
    - path: _test\.go
      text: "dot imports"

    # Exclude generated files
    - path: \.gen\.go
      linters:
        - all

    # Exclude protobuf files
    - path: \.pb\.go
      linters:
        - all

    # Exclude vendor
    - path: vendor/
      linters:
        - all

  # Independently of option `exclude` golangci-lint uses default exclude patterns
  exclude-use-default: false

  # Show statistics per linter
  exclude-dirs-use-default: true

severity:
  # Set default severity for issues
  default-severity: error

  # Severity rules
  rules:
    - linters:
        - dupl
      severity: info
    - linters:
        - gomnd
        - goconst
      severity: warning
